### PR TITLE
rbd: add CreateMirrorPeerBootstrapToken & ImportMirrorPeerBootstrapToken functions

### LINKED ISSUE #485: Missing rbd API components: mirror peer bootstrap
The rbd API implements function(s) below but go-ceph does not:
* rbd_mirror_peer_bootstrap_create
* rbd_mirror_peer_bootstrap_import

This issue has been filed to track implementing this missing
functionality in the appropriate package within go-ceph.
Please refer to the Ceph C API for details about the function(s)
in question.

NOTE: This issue was generated by a script.
If the content looks wrong or the wording seems a bit odd
please excuse the script and blame @phlogistonjohn

### PR DESCRIPTION
**Pull request by phlogistonjohn**
Depends on #494 

Resolves #485 

* Add CreateMirrorPeerBootstrapToken implementing rbd_mirror_peer_bootstrap_create
* Add ImportMirrorPeerBootstrapToken implementing rbd_mirror_peer_bootstrap_import
    
These functions can be used to set up mirroring between pools. Basic tests     included. The tests only verify that functions work, not that they     actually mirror data. That is a job for another day.

## Checklist
- [x] Added tests for features and functional changes
- [x] Public functions and types are documented
- [x] Standard formatting is applied to Go code

### CODE REVIEW

**Review by nixpanic — DISMISSED** [review]

**Comment by phlogistonjohn** [comment]
@mergifyio rebase

File: rbd/mirror.go [hunk 1]
```diff
@@ -514,3 +514,72 @@ func GetMirrorSiteName(conn *rados.Conn) (string, error) {
...
+
+// CreateMirrorPeerBootstrapToken returns a token value, representing the
+// cluster and pool associated with the given IO context,  that can be provided
+// to ImportMirrorPeerBootstrapToken in order to set up mirroring between
+// pools.
+//
+// Implements:
+//  int rbd_mirror_peer_bootstrap_create(
+//    rados_ioctx_t io_ctx, char *token, size_t *max_len);
+func CreateMirrorPeerBootstrapToken(ioctx *rados.IOContext) ([]byte, error) {
```
Comment (ansiwen) [inline rbd/mirror.go:526]: I believe returning the token as a string is more natural here, like for GetMirrorSiteName above.

File: rbd/mirror.go [hunk 2]
```diff
@@ -514,3 +514,72 @@ func GetMirrorSiteName(conn *rados.Conn) (string, error) {
...
+// pool associated with the IO context to create a mirroring relationship
+// between pools. The direction parameter controls if data in the pool is a
+// source, destination, or both.
+//
+// Implements:
+//  int rbd_mirror_peer_bootstrap_import(
+//    rados_ioctx_t io_ctx, rbd_mirror_peer_direction_t direction,
+//    const char *token);
+func ImportMirrorPeerBootstrapToken(
+	ioctx *rados.IOContext, direction MirrorPeerDirection, token []byte) error {
```
Comment (ansiwen) [inline rbd/mirror.go:572]: Same here, token should be a string.

**Review by ansiwen — CHANGES_REQUESTED** [review]

File: rbd/mirror.go (hunk 1 above)
Comment (phlogistonjohn) [reply rbd/mirror.go:526]: hehe. I went back and forth a bit on this myself and decided that because the token was supposed to be opaque it would be simpler to "round tip" and/or output to a file as bytes.
How strongly do you feel about this?

Comment (ansiwen) [reply rbd/mirror.go:526]: I don't think the token is opaque. It's clearly a Base64 string, that is meant to be inserted in json files.

Comment (ansiwen) [reply rbd/mirror.go:526]: Or does rbd_mirror_peer_bootstrap_create() return raw data and only the cli tool is converting it to Base64?

Comment (ansiwen) [reply rbd/mirror.go:526]: The python library also returns a string.

Comment (nixpanic) [reply rbd/mirror.go:526]: Maybe introduce a `MirrorPeerToken` type? It can have a `.String()` method and all if that is what users need later on.

Comment (ansiwen) [reply rbd/mirror.go:526]: But why? It is definitely a Base64 string. Actually even the encoded data is a string as well, because the token is a Base64v encoded json object. So it would be a string in any case. See https://github.com/ceph/ceph/blob/a67d1cf2a7a4031609a5d37baa01ffdfef80e993/src/librbd/api/Mirror.cc#L1316-L1318

Comment (nixpanic) [reply rbd/mirror.go:526]: I guess the question is if users are have a need to inspect the contents of the token. If the answer is *no*, then I do not see the need to provide details about it. In case the token needs to be exportable and consumed by an other application, then it makes sense to have it as a string.

Comment (phlogistonjohn) [reply rbd/mirror.go]: I have changed it to a string now. I was always on the fence about it, so it's no big deal to change. PTAL

**Review by nixpanic — APPROVED** [review]

**Review by ansiwen — APPROVED** [review]
LGTM
