### PR TITLE
rgw/admin: fix getbucketpolicy api

### LINKED ISSUE #882: Mismatched struct Policy vs Bucket in https://github.com/ceph/go-ceph/blob/master/rgw/admin/bucket.go
json: cannot unmarshal string into Go struct field Policy.owner of type struct { ID string "json:\"id\""; DisplayName string "json:\"display_name\"" }

### PR DESCRIPTION
**Pull request by thotz**
The request header in GetBucketPolicy(), was not passing policy in its
header, so the response received Bucket than the actual policy.

fixes #882

### CODE REVIEW

File: rgw/admin/bucket.go [hunk 1]
```diff
@@ -77,7 +77,11 @@ type Policy struct {
 		} `json:"grant_map"`
 	} `json:"acl"`
 	Owner struct {
-		ID          string `json:"id"`
+		ID struct {
+			ID      string `json:"id"`
+			Tentant string `json:"tenant"`
```
Comment (anoopcs9) [inline rgw/admin/bucket.go:82]:
```suggestion
			Tenant string `json:"tenant"`
```

**Review by anoopcs9 — CHANGES_REQUESTED** [review]

**Comment by anoopcs9** [comment]
Following diff is shown as the root cause of CI failures:
```diff rgw/admin/bucket.go.orig rgw/admin/bucket.go
--- rgw/admin/bucket.go.orig
+++ rgw/admin/bucket.go
@@ -78,9 +78,9 @@
 	} `json:"acl"`
 	Owner struct {
 		ID struct {
-			ID      string `json:"id"`
+			ID     string `json:"id"`
 			Tenant string `json:"tenant"`
-			NS      string `json:"ns"`
+			NS     string `json:"ns"`
 		} `json:"id"`
 		DisplayName string `json:"display_name"`
 	} `json:"owner"`
```

File: rgw/admin/bucket.go [hunk 2]
```diff
@@ -77,7 +77,11 @@ type Policy struct {
 		} `json:"grant_map"`
 	} `json:"acl"`
 	Owner struct {
-		ID          string `json:"id"`
+		ID struct {
+			ID     string `json:"id"`
+			Tenant string `json:"tenant"`
+			NS     string `json:"ns"`
+		} `json:"id"`
```
Comment (anoopcs9) [inline rgw/admin/bucket.go:84]: I see that the reporter complaining about mismatch in owner type for both Bucket and Policy struct. Can we check whether owner type is correct for Bucket struct too?

**Review by anoopcs9 — CHANGES_REQUESTED** [review]
I realized that we are missing a test for `GetBucketPolicy`. Can we add a very basic test to _bucket_test.go_? And while we are at it let's fix the following dead link from LINENO:116:
```
// GetBucketPolicy - http://docs.ceph.com/docs/mimic/radosgw/adminops/#get-bucket-or-object-policy
```

File: rgw/admin/bucket.go (hunk 2 above)
Comment (thotz) [reply rgw/admin/bucket.go:84]: Atleast from the docs owner is a string type https://docs.ceph.com/en/latest/radosgw/adminops/#get-bucket-info, not a container

**Comment by anoopcs9** [comment]
@Mergifyio rebase

**Review by anoopcs9 — APPROVED** [review]
lgtm.

**Review by phlogistonjohn — APPROVED** [review]
Code LGTM.

One test is failing but it appears to be due to trouble getting to the RPM repos on the ceph infra. I hope that retrying a few time will eventually resolve the issue.
